import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className='flex h-screen gap-20 items-center'>
            <div className='hidden md:block md:w-1/2 h-screen bg-primary'>
 
            </div>
            <div className="bg-white w-full md:w-1/2 max-w-xl overflow-auto">
                {children}
            </div>
        </div>

    )
}
