import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="flex justify-center items-center bg-none h-screen" style={{ background: 'url(/bgOne.jpg)' }}>
                <div className="absolute bg-black opacity-60 inset-0 z-0" />
                <div className="bg-white h-screen sm:h-[85%] p-10 lg:w-[50%] xl:w-[40%] overflow-auto rounded-xl z-1 shadow-2xl">
                    {children}
                </div>

            </body>
        </html>
    )
}
