import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div style={{ background: 'url(/bgOne.jpg)' }}>
            <div className='flex h-screen justify-center items-center'>
                <div className="fixed inset-0 bg-[rgba(0,0,0,.4)]" />
                <div className="bg-white p-10 h-[85%] lg:w-[50%] xl:w-[40%] overflow-auto rounded-xl shadow-2xl z-999">
                    {children}
                </div>
            </div>
        </div>

    )
}
