import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import ContextState from '../../components/system/context/contextStates'
import GlobalComponentsLayout from '../../components/system/pages/layouts/globalComponentsLayout/globalComponentsLayout'
import Provider from './sessionProvider'

import './tailwindImport.css'
import './globals.css'
import './fonts.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hamro Awaaj | Bridging Silence With Communication ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextState>
          <GlobalComponentsLayout>
            <Provider>
              {children}
            </Provider>
          </GlobalComponentsLayout>
        </ContextState>
      </body>
    </html>
  )
}
