import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import DashboardLayout from '../../../components/admin/pages/layouts/dashboardLayout/dashboardLayout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <main>
            <DashboardLayout>
                {children}
            </DashboardLayout>
        </main>
    )
}
