import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import DetailsFetcher from '../../../components/user/detailsFetcher/detailsFetcher'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <DetailsFetcher>
            {children}
        </DetailsFetcher>

    )
}
