import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import DetailsFetcher from '../../../components/user/detailsFetcher/detailsFetcher'
import ClientHeader from '../../../components/user/sections/header/header'
import ClientFooter from '../../../components/user/sections/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <DetailsFetcher>
            <ClientHeader isLoggedIn/>
                {children}
            <ClientFooter/>
        </DetailsFetcher>

    )
}
